<?php
/**
 * Copyright © Digital Rise Dorset. All rights reserved.YING.txt for license details.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
?>

<?php
/**
 * Copyright © Digital Rise Dorset. All rights reserved.YING.txt for license details.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);
 if ($block->getParentOrder()): ?>
    <div class="box-information">
        <strong><?= __('Subscription Parent Order:') ?></strong><br/>
        <a href="<?= $block->escapeUrl($block->getParentOrderUrl()) ?>">
            #<?= $block->getParentOrder()->getIncrementId() ?>
        </a>
    </div>
<?php
/**
 * Copyright © Digital Rise Dorset. All rights reserved.YING.txt for license details.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);
 endif; ?>
