<!-- view/frontend/templates/product/view/purchase_single_option.phtml -->
<?php
/**
 * Copyright © Digital Rise Dorset. All rights reserved.YING.txt for license details.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getLayout()->getBlock('product.info')->getProduct();
/** @var \Drd\Subscribe\ViewModel\ProductSubscription $viewModel */
$viewModel = $block->getData('viewModel');
$plans = $viewModel->getAssignedPlans($product);
$maxDiscount = $viewModel->getMaxSubscriptionDiscount($product);
?>

<?php
/**
 * Copyright © Digital Rise Dorset. All rights reserved.YING.txt for license details.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);
 if ($viewModel->isProductSubscriptionEnabled($product)): ?>

<div class="drd-subscribe">
    <div>
        <div class="field purchase-single-mode">
            <label>
                Or <?= $viewModel->getSubscribeLabel($product) ?>
            </label>
        </div>

        <div class="field subscription-plan">
            <div class="fieldset subscription">
                <?php
/**
 * Copyright © Digital Rise Dorset. All rights reserved.YING.txt for license details.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);
 foreach ($plans as $plan): ?>
                    <input type="hidden" name="subscription_plan_id" value="<?= $plan->getId() ?>">
                    <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>" />

                    <?php
/**
 * Copyright © Digital Rise Dorset. All rights reserved.YING.txt for license details.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);
 if ($plan->getTerms()): ?>
                        <a href="#" class="view-terms-link" data-cms-block="<?= $plan->getTerms() ?>">
                            Terms & Conditions
                        </a>
                    <?php
/**
 * Copyright © Digital Rise Dorset. All rights reserved.YING.txt for license details.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);
 endif; ?>
                <?php
/**
 * Copyright © Digital Rise Dorset. All rights reserved.YING.txt for license details.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);
 endforeach; ?>
            </div>
            <div class="subscription-action-one">
                <button type="submit" class="action primary big-subscribe-button" id="subscribe-button">
                    Subscribe
                </button>
            </div>
        </div>
    </div>
<?php
/**
 * Copyright © Digital Rise Dorset. All rights reserved.YING.txt for license details.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);
 endif; ?>
