<!-- view/frontend/templates/product/view/purchase_single_option.phtml -->
<?php
/**
 * Copyright © Digital Rise Dorset. All rights reserved.YING.txt for license details.
 * See COPYING.txt for license details.
 */
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getLayout()->getBlock('product.info')->getProduct();
/** @var \Drd\Subscribe\ViewModel\ProductSubscription $viewModel */
$viewModel = $block->getData('viewModel');
$plans = $viewModel->getAssignedPlans($product);
$maxDiscount = $viewModel->getMaxSubscriptionDiscount($product);
?>

<?php if ($viewModel->isProductSubscriptionEnabled($product)): ?>

<div class="drd-subscribe">
    <div>
        <div class="field purchase-single-mode">
            <label>
                Or <?= $viewModel->getSubscribeLabel($product) ?>
            </label>
        </div>

        <div class="field subscription-plan">
            <div class="fieldset subscription">
                <?php foreach ($plans as $plan): ?>
                    <input type="hidden" name="subscription_plan_id" value="<?= $plan->getId() ?>">
                    <?= $block->getBlockHtml('formkey') ?>

                    <?php if ($plan->getTerms()): ?>
                        <a href="#" class="view-terms-link" data-cms-block="<?= $plan->getTerms() ?>">
                            <?= __('Terms & Conditions') ?>
                        </a>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
            <div class="subscription-action-one">
                <button type="submit"
                        class="action primary big-subscribe-button"
                        id="subscribe-button"
                        data-role="subscribe-button"
                        data-mage-init='{"subscribeButton":{}}'>
                    <span><?= __('Subscribe') ?></span>
                    <div class="loader" style="display:none;">
                        <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                             alt="<?= $escaper->escapeHtmlAttr(__('Loading...')) ?>"
                             style="position: absolute;">
                    </div>
                </button>
            </div>
        </div>
    </div>
<?php endif; ?>
