<?php
/**
 * Copyright © Digital Rise Dorset. All rights reserved.YING.txt for license details.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Drd\Subscribe\ViewModel\SubscribeValidator $viewModel */
$viewModel = $block->getData('viewModel');
/** @var \Drd\Subscribe\ViewModel\ProductSubscription $subscriptionViewModel */
$subscriptionViewModel = $block->getData('subscriptionViewModel');
/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getLayout()->getBlock('product.info')->getProduct();
$maxDiscount = $subscriptionViewModel->getMaxSubscriptionDiscount($product);
?>
<?php

 if ($viewModel->isCustomerLoggedIn()): ?>
    <?= $block->getChildHtml(); ?>

    <div id="subscription-terms-modal" style="display:none;">
        <div class="content" id="subscription-terms-modal-content">Loading…</div>
    </div>

    <script type="text/x-magento-init">
        {
            "#subscription-terms-modal": {
                "Drd_Subscribe/js/subscribe-terms-modal": {}
            }
        }
    </script>
<?php else: ?>
    <?php if ($maxDiscount): ?>
    <div class="subscription-login-required">
        <?= __('Log in to Save up to %1 by Subscribing to this product', $maxDiscount) ?>
        <a href="<?= $escaper->escapeUrl($viewModel->getLoginUrl($block)) ?>"><?= __('Log In') ?></a>
    </div>
    <?php endif; ?>
<?php endif; ?>
