<?php
/**
 * Copyright © Digital Rise Dorset. All rights reserved.YING.txt for license details.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

/**
 * Copyright © Digital Rise Dorset. All rights reserved.YING.txt for license details.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */
$_item = $block->getItem();
/** @var \Drd\Subscribe\ViewModel\CartItemSubscriptionInfo $viewModel */
$viewModel = $block->getData('viewModel');
$label = $viewModel->getDiscountLabel($_item);
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $this->escapeHtml(__('Item')) ?>" class="col item">
        <?php if ($block->hasProductUrl()): ?>
        <a href="<?= $this->escapeUrl($block->getProductUrl()) ?>"
           title="<?= $this->escapeHtml($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo">
            <?php else: ?>
            <span class="product-item-photo">
            <?php endif; ?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()): ?>
        </a>
    <?php else: ?>
        </span>
    <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="<?= $this->escapeUrl($block->getProductUrl()) ?>"><?= $this->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?= $this->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>

            <?php if ($label): ?>
                <div class="subscription-discount-label"><?= $label ?></div>
            <?php endif; ?>

            <?php if ($_options = $block->getOptionList()): ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option): ?>
                        <?php $_formatedOptionValue = $viewModel->getFormatedOptionValue($block, $_option) ?>
                        <dt><?= $this->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?= $this->escapeHtml($_formatedOptionValue['full_view'], ['span', 'a']) ?>
                            <?php else: ?>
                                <?= $this->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class= "cart item message <?= $this->escapeHtmlAttr($message['type']) ?>">
                        <div><?= $this->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif; ?>
        </div>
    </td>

    <?php if ($canApplyMsrp): ?>
        <td class="col msrp" data-th="<?= $this->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $this->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($this->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "origin": "info",
                                            "helpLinkId": "#<?= $this->escapeJs($this->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $this->escapeJs($this->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $this->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
        </td>
    <?php else: ?>
        <td class="col price" data-th="<?= $this->escapeHtml(__('Price')) ?>">
            <?= $block->getUnitPriceHtml($_item) ?>
        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?= $this->escapeHtml(__('Qty')) ?>">
        <div class="field qty">
            <div class="control qty">
                <label for="cart-<?= $this->escapeHtmlAttr($_item->getId()) ?>-qty">
                    <span class="label"><?= $this->escapeHtml(__('Qty')) ?></span>
                    <input id="cart-<?= $this->escapeHtmlAttr($_item->getId()) ?>-qty"
                           name="cart[<?= $this->escapeHtmlAttr($_item->getId()) ?>][qty]"
                           data-cart-item-id="<?= $this->escapeHtmlAttr($_item->getSku()) ?>"
                           value="<?= $this->escapeHtmlAttr($block->getQty()) ?>"
                           type="number"
                           min="0"
                           size="4"
                           step="any"
                           title="<?= $this->escapeHtmlAttr(__('Qty')) ?>"
                           class="input-text qty"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-item-qty="<?= $this->escapeHtmlAttr($block->getQty()) ?>"
                           data-role="cart-item-qty"/>
                </label>
            </div>
        </div>
    </td>

    <td class="col subtotal" data-th="<?= $this->escapeHtml(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>
</tr>
<tr class="item-actions">
    <td colspan="4">
        <div class="actions-toolbar">
            <?= /* @noEscape */ $block->getActions($_item) ?>
        </div>
    </td>
</tr>
</tbody>
