<?php
/**
 * Copyright © Digital Rise Dorset. All rights reserved.YING.txt for license details.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var \Magento\Framework\View\Element\Template $block */
?>

<?php if ($block->getParentOrder()): ?>
    <div class="box-information">
        <strong><?= __('Subscription Parent Order:') ?></strong><br/>
        <a href="<?= $escaper->escapeUrl($block->getParentOrderUrl()) ?>">
            #<?= $block->getParentOrder()->getIncrementId() ?>
        </a>
    </div>
<?php endif; ?>
